---
name: general
"on": pull_request
permissions:
  contents: read
  packages: read
jobs:
  MCVS-general-action:
    strategy:
      matrix:
        args:
          - testing-type: lint-commit
          - testing-type: lint-git
          - testing-type: yamllint
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      # yamllint disable-line rule:line-length
      - uses: schubergphilis/mcvs-general-action@5be6cc746008ec82646e52cf7e07770a7ed7c7eb # v0.7.0
        with:
          testing-type: ${{ matrix.args.testing-type }}
